# Generated by Django 4.2.2 on 2023-06-24 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='contract',
            field=models.ImageField(blank=True, upload_to='contract_images/', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='route_link',
            field=models.URLField(blank=True, verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='route',
            field=models.ImageField(blank=True, upload_to='route_images/', verbose_name='Фото маршрута'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принят')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='web.orders', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(upload_to='profile_images/', verbose_name='Фото ')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('document', models.ImageField(blank=True, upload_to='route_images/', verbose_name='Документ')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profession', verbose_name='Специализация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile', verbose_name='Исполнитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='completed_orders/', verbose_name='Фото №1')),
                ('photo_2', models.ImageField(upload_to='completed_orders/', verbose_name='Фото №2')),
                ('photo_3', models.ImageField(upload_to='completed_orders/', verbose_name='Фото №3')),
                ('photo_4', models.ImageField(blank=True, upload_to='completed_orders/', verbose_name='Фото №4')),
                ('photo_5', models.ImageField(blank=True, upload_to='completed_orders/', verbose_name='Фото №5')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('rate', models.PositiveIntegerField(verbose_name='Оценка заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.orders')),
            ],
            options={
                'verbose_name': 'Выполненный заказ',
                'verbose_name_plural': 'Выполненный заказ',
            },
        ),
    ]
